### ISSUE TITLE
refresh zlayermanager window and layers when changing subtool

### ISSUE THREAD

**Issue by navarrogar** [JonasOuellet/zlayermanager#10]
Hi Jonas,
Thank you so much for your work on this plugin is really good.
I am one of the lead character modellers at DNEG feature animation, and I just found out about your plugin.
I was wondering if the plugin window could refresh automatically when switching subtool. Or maybe there could be a dropdown where we can switch subtool.

Thank you for your time!
/Angel Navarro

**Comment by JonasOuellet** [comment]
Hello Angel,  Glad you like it.  I just release a test version with the new subtool feature.    You should see a drop down with all the avaible subtool, you can activate the subtool you want from the list.

![image](https://user-images.githubusercontent.com/10328303/224594006-799e1072-9239-4140-b898-b9a4beebb2e1.png)


To download the test version go to the release page and download the .zip.  Extract it in your zbrush folder.

**Comment by JonasOuellet** [comment]
I Just fixed the popup.  I will release it later.

**Comment by JonasOuellet** [comment]
Hello Angel,

I released a new test version.  Also added the subdiv slider to the ui.

See the release page to download the version.

![image](https://user-images.githubusercontent.com/10328303/224870098-925ba278-aa25-4325-b540-bdbea5f03bde.png)
